chore: update to keycloak 25
defenseunicorns/uds-identity-config pull request #207
Opened 2024-09-03 18:36 UTC by rjferguson21

## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md)(https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md#submitting-a-pull-request) followed

2024-09-04 19:41 UTC, UnicornChance approved these changes
lgtm, testing locally and everything is working as expected with integration tests and manual eye ball tests.

2024-09-04 22:08 UTC, mjnagel requested changes
Not sure where to leave this comment - two fields now showing in the account UI that I think we can leave off from displaying there:
- anti-bot location
- access request notes

Also maybe a broader question on that UI and our strategy on what is exposed to the end user for editing - the rank/affiliation fields for example, should those be editable by the end user?

2024-09-05 14:09 UTC, mjnagel approved these changes

2024-09-05 14:09 UTC, UnicornChance approved these changes

2024-09-05 14:28 UTC, merged